### ISSUE TITLE
Memory Issues on applications with large collections upon restarting docker

### ISSUE THREAD

**Issue by fahadmalikawan** [exadel-inc/CompreFace#1094]
**Description**

I have compreface application with few hundred thousand subjects. which works normally flawless. But if I attempt to restart or down and up the docker. Those large collection applications fails to provide recognition (Error details attached). However I am still able to add more subjects. And the applications with smaller collection have no issues recognizing faces.

I used to have 2 processes and 2 threads. Each process occupies almost 4GB of my GPU memory. GPU has 12GB available memory (RTX 3060 12GB)

**Background**
I have built a system which stores every face captured in some public cameras into an FTP folder. Each image is just an inch small sized  about 12 KB - 25 KB. A script runs continuously to add those faces into an application.
Upon reaching about 700,000 faces. It is working pretty fast. The recognition service is utilized only upon request. i.e. the user attempt to search someone by image. the system tells the occurrences of that person by running recognition service in that application.
I found that the Swap memory was full, so I restarted the docker. after that, the docker failed to provide search (recognition) in that application. I tried restarting several times but still got the issue. However the issue resolved automatically after few hours.
Note: i have another application with very small collection i.e. 10-15 subjects only. No issues on searching in that application. which concludes that the docker is running fine.
I tried 3 times restarting docker when it was running normally. Each time. it went into that error state where it is unable to recognize faces in the large collection.
I checked the logs. In the long details, I found this text "**Caused by: java.lang.OutOfMemoryError: Java heap space**".
So I split the subjects into two different applications by manually running query to update API_KEY in the subject table. Issue still persisted.
I have a lot of RAM available. I don't know where i am making mistake. The search is fast. The RAM is available. I am wondering if the subjects are loaded into GPU RAM which is only 8 GB then it might be the issue. But if it is loaded into System RAM which is 64GB and a small portion is utilized only. Rest is free. 

Here is my docker-compose.yml file:

version: '3.4'

volumes:
  postgres-data:

services:
  compreface-postgres-db:
    image: ${registry}compreface-postgres-db:${POSTGRES_VERSION}
    restart: always
    container_name: "compreface-postgres-db"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  compreface-admin:
    image: ${registry}compreface-admin:${ADMIN_VERSION}
    restart: always
    container_name: "compreface-admin"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=${enable_email_server}
      - EMAIL_HOST=${email_host}
      - EMAIL_USERNAME=${email_username}
      - EMAIL_FROM=${email_from}
      - EMAIL_PASSWORD=${email_password}
      - ADMIN_JAVA_OPTS=${compreface_admin_java_options}
      - MAX_FILE_SIZE=${max_file_size}
      - MAX_REQUEST_SIZE=${max_request_size}B
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:
    image: ${registry}compreface-api:${API_VERSION}
    restart: always
    container_name: "compreface-api"
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=${compreface_api_java_options}
      - SAVE_IMAGES_TO_DB=${save_images_to_db}
      - MAX_FILE_SIZE=${max_file_size}
      - MAX_REQUEST_SIZE=${max_request_size}B
      - CONNECTION_TIMEOUT=${connection_timeout:-10000}
      - READ_TIMEOUT=${read_timeout:-60000}

  compreface-fe:
    image: ${registry}compreface-fe:${FE_VERSION}
    restart: always
    container_name: "compreface-ui"
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin
    environment:
      - CLIENT_MAX_BODY_SIZE=${max_request_size}
      - PROXY_READ_TIMEOUT=${read_timeout:-60000}ms
      - PROXY_CONNECT_TIMEOUT=${connection_timeout:-10000}ms

  compreface-core:
    image: ${registry}compreface-core:${CORE_VERSION}
    restart: always
    container_name: "compreface-core"
    runtime: nvidia
    environment:
      - ML_PORT=3000
      - UWSGI_PROCESSES=${uwsgi_processes:-2}
      - UWSGI_THREADS=${uwsgi_threads:-1}

yns@faceserver:/var/CompreFace_1.1.0/custom-builds/SubCenter-ArcFace-r100-gpu$ ls
docker-compose.yml
yns@faceserver:/var/CompreFace_1.1.0/custom-builds/SubCenter-ArcFace-r100-gpu$ cat docker-compose.yml
version: '3.4'

volumes:
  postgres-data:

services:
  compreface-postgres-db:
    image: ${registry}compreface-postgres-db:${POSTGRES_VERSION}
    restart: always
    container_name: "compreface-postgres-db"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  compreface-admin:
    image: ${registry}compreface-admin:${ADMIN_VERSION}
    restart: always
    container_name: "compreface-admin"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=${enable_email_server}
      - EMAIL_HOST=${email_host}
      - EMAIL_USERNAME=${email_username}
      - EMAIL_FROM=${email_from}
      - EMAIL_PASSWORD=${email_password}
      - ADMIN_JAVA_OPTS=${compreface_admin_java_options}
      - MAX_FILE_SIZE=${max_file_size}
      - MAX_REQUEST_SIZE=${max_request_size}B
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:
    image: ${registry}compreface-api:${API_VERSION}
    restart: always
    container_name: "compreface-api"
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=${compreface_api_java_options}
      - SAVE_IMAGES_TO_DB=${save_images_to_db}
      - MAX_FILE_SIZE=${max_file_size}
      - MAX_REQUEST_SIZE=${max_request_size}B
      - CONNECTION_TIMEOUT=${connection_timeout:-10000}
      - READ_TIMEOUT=${read_timeout:-60000}

  compreface-fe:
    image: ${registry}compreface-fe:${FE_VERSION}
    restart: always
    container_name: "compreface-ui"
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin
    environment:
      - CLIENT_MAX_BODY_SIZE=${max_request_size}
      - PROXY_READ_TIMEOUT=${read_timeout:-60000}ms
      - PROXY_CONNECT_TIMEOUT=${connection_timeout:-10000}ms

  compreface-core:
    image: ${registry}compreface-core:${CORE_VERSION}
    restart: always
    container_name: "compreface-core"
    runtime: nvidia
    environment:
      - ML_PORT=3000
      - UWSGI_PROCESSES=${uwsgi_processes:-2}
      - UWSGI_THREADS=${uwsgi_threads:-1}

-----------------------------------------------------------

In the .env file. I set 2 processes and 2 threads. So GPU with 12GB memory is used around 8GB.
Also tried with 1 thread.

**To Reproduce**

Add few hundred thousand subjects into a single recognition service.
Try to search (recognize) into that collection. It will run fine.
Then run:
- sudo docker compose down
- sudo docker compose up -d

I may go into that error state. watch the logs by not running docker in detached mode.

**Screenshots**
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/864e109d-9944-44d9-8094-fd1dc83cff05)
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/d3a75319-0d1d-42ad-b0d8-9ee8c5b3ee9e)
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/52ace78d-8117-489e-8f32-472cfb1690ff)
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/e7a82842-a34d-4a17-81e6-13ad3968e0c5)
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/454e36d6-010c-4e2b-b5ea-8d7c0594e404)
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/cfdf28ac-4fda-43b0-85d7-f2bb5b277544)
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/dc7c950f-4bae-4c07-8b9c-b08f59494096)

Memory seems to be available in docker stats. Here is the screenshot:
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/9f16387f-3c41-49e3-af0b-7fb3cf172050)

Errors in the last 2-3 screenshots
I am also attaching a file where I copied the logs. It might be not in order and may have two different type of errors. Might be helpful.

A screenshot of pictures I add as subjects:
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/f42274ea-5801-446f-8843-771c69fe95d3)

**Desktop (please complete the following information):**

 - OS: Ubuntu Server 22.04
 - CPU: i7-13700k
 - Memory: Corsair Vengeance 64GB(16x4) DDR-5 5600 MHz
 - Mainboard: Gigabyte Z790
 - Disk: Samsung 980 Pro 2TB Gen-4 NVME
 - GPU: Nvidia RTX 3060 (12GB)

**Logs**

compreface-core         | [08:28:58] ../src/nnvm/legacy_json_util.cc:208: Loading symbol save                                         d by previous version v1.3.0. Attempting to upgrade...
compreface-core         | [08:28:58] ../src/nnvm/legacy_json_util.cc:216: Symbol successfully                                          upgraded!
compreface-core         | [08:28:58] ../src/engine/engine.cc:54: MXNet start using engine: Th                                         readedEnginePerDevice
compreface-core         | [08:28:58] ../src/base.cc:79: cuDNN lib mismatch: linked-against ve                                         rsion 8101 != compiled-against version 8100.  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this wa                                         rning.
compreface-core         | [32, 16, 8] {'32': {'SCALES': (32, 16), 'BASE_SIZE': 16, 'RATIOS':                                          (1.0,), 'ALLOWED_BORDER': 9999}, '16': {'SCALES': (8, 4), 'BASE_SIZE': 16, 'RATIOS': (1.0,),                                          'ALLOWED_BORDER': 9999}, '8': {'SCALES': (2, 1), 'BASE_SIZE': 16, 'RATIOS': (1.0,), 'ALLOWED_                                         BORDER': 9999}}
compreface-core         | use_landmarks True
compreface-core         | {"severity": "DEBUG", "message": "Found: BoundingBoxDTO(x_min=75, y                                         _min=75, x_max=189, y_max=237, probability=0.9996106028556824, _np_landmarks=array([[ 88.7701                                         6 , 139.92479 ],\n       [132.1026  , 139.6305  ],\n       [ 95.158104, 168.16205 ],\n                                                [ 92.093605, 199.50085 ],\n       [124.6178  , 199.58165 ]], dtype=float32))", "request": {"m                                         ethod": "POST", "path": "/find_faces", "filename": "download (2).jpeg", "api_key": "", "remot                                         e_addr": "172.26.0.4"}, "logger": "src.services.facescan.plugins.insightface.insightface", "m                                         odule": "insightface", "traceback": null, "build_version": "dev"}
compreface-core         | [08:29:00] ../src/nnvm/legacy_json_util.cc:203: Warning: loading sy                                         mbol saved by MXNet version 20000 with lower version of MXNet v10900. May cause undefined beh                                         avior. Please update MXNet if you encounter any issue
compreface-core         | [08:29:01] ../src/nnvm/legacy_json_util.cc:208: Loading symbol save                                         d by previous version v1.3.0. Attempting to upgrade...
compreface-core         | [08:29:01] ../src/nnvm/legacy_json_util.cc:216: Symbol successfully                                          upgraded!
compreface-core         | {"severity": "INFO", "message": "200 OK", "request": {"method": "PO                                         ST", "path": "/find_faces", "filename": "download (2).jpeg", "api_key": "", "remote_addr": "1                                         72.26.0.4"}, "logger": "src.services.flask_.log_response", "module": "log_response", "traceba                                         ck": null, "build_version": "dev"}
compreface-admin        | 2023-06-27 08:29:57.914  INFO 7 --- [nio-8080-exec-4] o.s.s.o.p.tok                                         en.store.JdbcTokenStore     : Failed to find access token
compreface-ui           | 10.10.4.189 - CommonClientId [27/Jun/2023:08:29:57 +0000] "POST /ad                                         min/oauth/token?grant_type=refresh_token&scope=all HTTP/1.1" 200 0 "http://10.10.100.10:8000/                                         test-model?app=98e2ec93-9699-4be7-b173-960364144550&model=f5d4370c-0a46-4b6f-bbe8-af41b28bb3d                                         a&type=RECOGNITION" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, lik                                         e Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0"
compreface-ui           | 2023/06/27 08:29:58 [error] 26#26: *17 upstream timed out (110: Con                                         nection timed out) while reading response header from upstream, client: 10.10.4.189, server:                                          ui, request: "POST /api/v1/recognition/recognize?face_plugins=landmarks&face_plugins=gender&f                                         ace_plugins=age HTTP/1.1", upstream: "http://172.26.0.4:8080/api/v1/recognition/recognize?fac                                         e_plugins=landmarks&face_plugins=gender&face_plugins=age", host: "10.10.100.10:8000", referre                                         r: "http://10.10.100.10:8000/test-model?app=98e2ec93-9699-4be7-b173-960364144550&model=f5d437                                         0c-0a46-4b6f-bbe8-af41b28bb3da&type=RECOGNITION"
compreface-ui           | 10.10.4.189 - - [27/Jun/2023:08:29:58 +0000] "POST /api/v1/recognit                                         ion/recognize?face_plugins=landmarks&face_plugins=gender&face_plugins=age HTTP/1.1" 504 562 "                                         http://10.10.100.10:8000/test-model?app=98e2ec93-9699-4be7-b173-960364144550&model=f5d4370c-0                                         a46-4b6f-bbe8-af41b28bb3da&type=RECOGNITION" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Apple                                         WebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0"
compreface-api          | Exception in thread "http-nio-8080-Poller" Exception in thread "Cat                                         alina-utility-1" java.lang.OutOfMemoryError: Java heap space
compreface-api          | java.lang.OutOfMemoryError: Java heap space
compreface-api          | 2023-06-27 08:30:47.681 ERROR 6 --- [nio-8080-exec-1] c.e.f.c.h.Res                                         ponseExceptionHandler       : Undefined exception occurred
compreface-api          |
compreface-api          | org.springframework.web.util.NestedServletException: Handler dispat                                         ch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
compreface-api          |       at org.springframework.web.servlet.DispatcherServlet.doDispat                                         ch(DispatcherServlet.java:1082)
compreface-api          |       at org.springframework.web.servlet.DispatcherServlet.doServic                                         e(DispatcherServlet.java:963)
compreface-api          |       at org.springframework.web.servlet.FrameworkServlet.processRe                                         quest(FrameworkServlet.java:1006)
compreface-api          |       at org.springframework.web.servlet.FrameworkServlet.doPost(Fr                                         ameworkServlet.java:909)
compreface-api          |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:68                                         1)
compreface-api          |       at org.springframework.web.servlet.FrameworkServlet.service(F                                         rameworkServlet.java:883)
compreface-api          |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:76                                         4)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.internalDo                                         Filter(ApplicationFilterChain.java:227)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(A                                         pplicationFilterChain.java:162)
compreface-api          |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFil                                         ter.java:53)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.internalDo                                         Filter(ApplicationFilterChain.java:189)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(A                                         pplicationFilterChain.java:162)
compreface-api          |       at com.exadel.frs.core.trainservice.filter.SecurityValidation                                         Filter.doFilter(SecurityValidationFilter.java:134)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.internalDo                                         Filter(ApplicationFilterChain.java:189)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(A                                         pplicationFilterChain.java:162)
compreface-api          |       at org.springframework.web.filter.RequestContextFilter.doFilt                                         erInternal(RequestContextFilter.java:100)
compreface-api          |       at org.springframework.web.filter.OncePerRequestFilter.doFilt                                         er(OncePerRequestFilter.java:117)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.internalDo                                         Filter(ApplicationFilterChain.java:189)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(A                                         pplicationFilterChain.java:162)
compreface-api          |       at org.springframework.web.filter.FormContentFilter.doFilterI                                         nternal(FormContentFilter.java:93)
compreface-api          |       at org.springframework.web.filter.OncePerRequestFilter.doFilt                                         er(OncePerRequestFilter.java:117)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.internalDo                                         Filter(ApplicationFilterChain.java:189)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(A                                         pplicationFilterChain.java:162)
compreface-api          |       at org.springframework.boot.actuate.metrics.web.servlet.WebMv                                         cMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
compreface-api          |       at org.springframework.web.filter.OncePerRequestFilter.doFilt                                         er(OncePerRequestFilter.java:117)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.internalDo                                         Filter(ApplicationFilterChain.java:189)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(A                                         pplicationFilterChain.java:162)
compreface-api          |       at org.springframework.web.filter.CharacterEncodingFilter.doF                                         ilterInternal(CharacterEncodingFilter.java:201)
compreface-api          |       at org.springframework.web.filter.OncePerRequestFilter.doFilt                                         er(OncePerRequestFilter.java:117)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.internalDo                                         Filter(ApplicationFilterChain.java:189)
compreface-api          |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(A                                         pplicationFilterChain.java:162)
compreface-api          |       at org.apache.catalina.core.StandardWrapperValve.invoke(Stand                                         ardWrapperValve.java:197)
compreface-api          |       at org.apache.catalina.core.StandardContextValve.invoke(Stand                                         ardContextValve.java:97)
compreface-api          |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke                                         (AuthenticatorBase.java:541)
compreface-api          |       at org.apache.catalina.core.StandardHostValve.invoke(Standard                                         HostValve.java:135)
compreface-api          |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorRe                                         portValve.java:92)
compreface-api          |       at org.apache.catalina.core.StandardEngineValve.invoke(Standa                                         rdEngineValve.java:78)
compreface-api          |       at org.apache.catalina.connector.CoyoteAdapter.service(Coyote                                         Adapter.java:360)
compreface-api          |       at org.apache.coyote.http11.Http11Processor.service(Http11Pro                                         cessor.java:399)
compreface-api          |       at org.apache.coyote.AbstractProcessorLight.process(AbstractP                                         rocessorLight.java:65)
compreface-api          |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.proce                                         ss(AbstractProtocol.java:890)
compreface-api          |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doR                                         un(NioEndpoint.java:1743)
compreface-api          |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketP                                         rocessorBase.java:49)
compreface-api          |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorke                                         r(ThreadPoolExecutor.java:1191)
compreface-api          |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.r                                         un(ThreadPoolExecutor.java:659)
compreface-api          |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable                                         .run(TaskThread.java:61)
compreface-api          |       at java.base/java.lang.Thread.run(Unknown Source)
compreface-api          | Caused by: java.lang.OutOfMemoryError: Java heap space
compreface-api          |
compreface-api          | 2023-06-27 08:31:32.601 ERROR 6 --- [alina-utility-3] o.a.coyote.ht                                         tp11.Http11NioProtocol      : Error processing async timeouts
compreface-api          |
compreface-api          | java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError                                         : Java heap space
compreface-api          |       at java.base/java.util.concurrent.FutureTask.report(Unknown S                                         ource)
compreface-api          |       at java.base/java.util.concurrent.FutureTask.get(Unknown Sour                                         ce)
compreface-api          |       at org.apache.coyote.AbstractProtocol.startAsyncTimeout(Abstr                                         actProtocol.java:632)
compreface-api          |       at org.apache.coyote.AbstractProtocol.lambda$start$0(Abstract                                         Protocol.java:617)
compreface-api          |       at java.base/java.util.concurrent.Executors$RunnableAdapter.c                                         all(Unknown Source)
compreface-api          |       at java.base/java.util.concurrent.FutureTask.runAndReset(Unkn                                         own Source)
compreface-api          |       at java.base/java.util.concurrent.ScheduledThreadPoolExecutor                                         $ScheduledFutureTask.run(Unknown Source)
compreface-api          |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorke                                         r(Unknown Source)
compreface-api          |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.r                                         un(Unknown Source)
compreface-api          |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable                                         .run(TaskThread.java:61)
compreface-api          |       at java.base/java.lang.Thread.run(Unknown Source)
compreface-api          | Caused by: java.lang.OutOfMemoryError: Java heap space
compreface-api          |
compreface-admin        | 2023-06-27 08:34:57.836  INFO 7 --- [io-8080-exec-10] o.s.s.o.p.tok                                         en.store.JdbcTokenStore     : Failed to find access token
compreface-ui           | 10.10.4.189 - CommonClientId [27/Jun/2023:08:34:57 +0000] "POST /ad                                         min/oauth/token?grant_type=refresh_token&scope=all HTTP/1.1" 200 0 "http://10.10.100.10:8000/                                         test-model?app=98e2ec93-9699-4be7-b173-960364144550&model=f5d4370c-0a46-4b6f-bbe8-af41b28bb3d                                         a&type=RECOGNITION" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, lik                                         e Gecko) Chrome/113.0.0.0 Safari/537.36 OPR/99.0.0.0"

**Another log error I found:**
I found another issue during testing and restarting etc. which was different from out of memory. Attached in the file (See in the end of the file)
[docker error.txt](https://github.com/exadel-inc/CompreFace/files/11925207/docker.error.txt)
A small screenshot:
![image](https://github.com/exadel-inc/CompreFace/assets/94027725/9ca66d4e-f2fb-4103-8b4c-b3ed63b06292)

**Additional context**

Please guide what to do. or is it some bug to be fixed in the next version?
The out of memroy issue is strange. i can see in the docker stats. all 62GB is assigned to the containers. Is it storing data in the main RAM of the GPU RAM. If GPU RAM. Then the reason is obvious. I will use 3090 then. which has 24GB memory
And if it is using System RAM. I will upgrade to 128 GB or higher. but that doesn't seem to be the problem. i sill have free RAM availble in the system monitoring.

**Comment by fahadmalikawan** [comment]
It turned out to be the issue with the heap memory allocated at max 8GB to compreface-api.
I changed that with different high allocations i.e 40GB, 32GB, 24GB, 16GB etc by changing:
compreface_api_java_options=-Xmx8g
to
compreface_api_java_options=-Xmx16g

After that, java.lang.OutOfMemoryError: Java heap space no longer showed.

BUT

after the docker starts, compreface-api container start populating RAM with the subjects for few minutes, then the recognition works fine. but randomly it releases all the memory. and the recognition also fails. then again starts loading subjects into memory.

One thing is clear, the issue is with the System RAM management, not the GPU

Need further assistant please.

**Comment by pospielov** [comment]
I explained [here](https://github.com/exadel-inc/CompreFace/discussions/1070) that the practical limit is about 200 000 faces
Do you have any errors after you increased the memory limit? 
I am almost sure the problem is with memory again, but I need logs to make sure.
